// const promise = new Promise((resolve,reject) => {
//   let a=1+3;
//   if(a===3) {
//     const obj={
//       operation:"addition",
//       result:3,
//       expression:"a=1+2"
//     }
//     resolve(obj)
//   }
//   else {
//     reject(new Error('operation was terminated due to wrong result'))
//   }
// })
// promise
// .then((returnObject) => {
//   console.log(returnObject)
// })
// .catch((error) => {
//   console.log(error.message)
// })

const userLeft = false;
const userWatchingCatMeme = false;

function watchTutorialCallBack() {
  return new Promise((resolve,reject) => {
     if (userLeft) {
    reject({
      name: 'user left',
      message: ':('
    })
  }
  else if (userWatchingCatMeme) {
    reject({
      name: 'user Watching cat meme',
      message: 'webDev <cat meme'
    })
  }
  else {
    resolve('thumbs up and subscribe');
  }

  })
}

watchTutorialCallBack().then((message) => {
  console.log('success '+message)
})
.catch((error) => {
  console.log(error.name +" "+error.message)
})